var element = {};
element.Caption = "<h4>{{value}}</h4>";

element.Type    = "<label>Type:</label>"
                + "<input value='{{value}}' "
                + "  class='type' "
                + "  data-subkey='Type'  "
                + "  data-type='{{type}}' "
                + "  required={{required}}>";

element.Unit    = "<label>Unit:</label>"
                + "<input data-type='{{type}}' "
                + "  value='{{value}}' "
                + "  data-subkey='Unit' "
                + "  class='unit' "
                + "  list='unit-{{key}}' "
                + "  required={{required}}>"
                + "<datalist id='unit-{{key}}'>"
                + "{{#each options}}"
                + "   <option value='{{this}}'>"
                + "{{/each}}"
                + "</datalist>";

element.Value   = "<label>Value:</label>"
                + "<input "
                + "  data-type='{{type}}' "
                + "  data-subkey='Value' "
                + "  value='{{value}}' "
                + "  required={{required}}"
                + "  pattern='[+-]?[0-9]{0,5}[\.][0-9]{0,5}[eE]?[+-]?[0-9]{1,3}' "
                + "  class='val'>";

element.Comment = "<label>Comment:</label>"
                + "<input "
                + "  data-type='{{type}}'"
                + "  placeholder='comment the point' "
                + "  data-subkey='Comment' "
                + "  class='comment'"
                + "  value='{{value}}'"
                + "  required={{required}}>";

element.Document    = "{{#each this}}"
                    + "<tr>"
                    + "<td>{{Customer}}</td>"
                    + "<td>{{Device}}</td>"
                    + "<td>{{ToDoType}}</td>"
                    + "<td>{{Sign}}</td>"
                    + "<td>{{Year}}</td>"
                    + "<td>"
                    + "<a href='http://localhost:5984/_utils/fauxton/index.html#/database/mp_db/{{Id}}' target='_blank'>Couch"
                    + "</a>"
                    + "</td>"
                    + "<td><button"
                    + "   data-parent = 'td'"
                    + "   data-method ='PUT' "
                    + "   data-url= '{{id}}/button'"
                    + "   data-key='{{key}}'"
                    + "   data-cmd='load'"
                    + "   data-api='/{{id}}/id/{{Id}}' "
                    + "   type='submit'>+</button>"
                    + "</td>"
                    + "<td><button "
                    + "   data-method='DELETE' "
                    + "   type='submit'>-</button></td>"
                    + "</tr>"
                    + "{{/each}}"
exports.element = element;

var display = {};
display.section   = "<section>"
                  + "{{{Caption}}}"
                  + "{{{Type}}}"
                  + "{{{Unit}}}"
                  + "{{{Value}}}"
                  + "{{{Comment}}}"
                  + "<button "
                  + "  data-parent  = 'section'"
                  + "  data-url     = '/{{id}}/section' "
                  + "  data-id      = '{{id}}'"
                  + "  data-key     = '{{key}}'"
                  + "  data-method  = 'POST' "
                  + "  type='submit'>ok"
                  + "</button>"
                  + "</section>";

display.documentSelect = "<table summary='select or deselect calibration documents from table'>"
                       + "<caption>select or deselect calibration documents from table</caption>"
                       + "<colgroup/>"
                       + "<colgroup title='title' span='2'/>"
                       + "<thead>"
                       + "<tr>"
                       + "<th scope='col'>Customer</th>"
                       + "<th scope='col'>Device</th>"
                       + "<th scope='col'>ToDoType</th>"
                       + "<th scope='col'>Sign</th>"
                       + "<th scope='col'>Year</th>"
                       + "<th scope='col'>Details</th>"
                       + "<th scope='col'>select</th>"
                       + "<th scope='col'>deselect</th>"
                       + "</tr>"
                       + "</thead>"
                       + "<tbody>"
                       + "{{{Document}}}"
                       + "</tbody>"
                       + "</table>";

exports.display = display;

exports.state = "<h2>state of container {{no}}</h2>"
              + "<p>{{#each}}"
              + "<div class='serial'>{{#each this}}"
              + "<div class='{{this}} parallel'>{{this}}</div>"
              + "{{/each}}</div>"
              + "{{/each}}</p>";


exports.main ="<!DOCTYPE HTML>"
             + "<html>"
             + "<head>"
             + "<meta http-equiv='Content-Type' content='text/html; charset=UTF-8' />"
             + "<link type='text/css' rel='stylesheet'  href='../../css/main.css' />"
             + "<title>{{Name}}</title>"
             + "</head>"
             + "<body>"
             + "<header>"
             + "<h1>{{Name}}</h1>"
             + "<h2>{{Description}}</h2>"
             + "</header>"
             + "<nav>"
             + "<ul>"
             + "{{#each Title}} "
             + "<li><a href='../io/{{@index}}'>{{this}}</a></li>"
             + "{{/each}}"
             + "</ul>"
             + "</nav>"
             + "<aside class='ctrls'>"
             + "<ul>"
             + "<li><button"
             + "  data-parent  = 'li'"
             + "  data-url     = '/{{Id}}/button' "
             + "  data-api      = '/{{Id}}/ctrl/{{no}}'"
             + "  data-cmd     = 'load'"
             + "  data-method  = 'PUT' "
             + ">load</button></li>"
             + "<li><button"
             + "  data-parent  = 'li'"
             + "  data-url     = '/{{Id}}/button' "
             + "  data-api      = '/{{Id}}/ctrl/{{no}}'"
             + "  data-cmd     = 'run'"
             + "  data-method  = 'PUT' "
             + ">run</button></li>"
             + "<li><button"
             + "  data-parent  = 'li'"
             + "  data-url     = '/{{Id}}/button' "
             + "  data-api      = '/{{Id}}/ctrl/{{no}}'"
             + "  data-cmd     = 'pause'"
             + "  data-method  = 'PUT' "
             + ">pause</button></li>"
             + "<li><button"
             + "  data-parent  = 'li'"
             + "  data-url     = '/{{Id}}/button' "
             + "  data-api      = '/{{Id}}/ctrl/{{no}}'"
             + "  data-cmd     = 'stop'"
             + "  data-method  = 'PUT' "
             + ">stop</button></li>"
             + "</ul>"
             + "</aside>"
             + "<main id='content' class='{{page}}'>"
             + "<a href='/{{Id}}/content/{{page}}/{{no}}'>{{page}}/{{no}}</a>"
             + "</main>"
             + "<aside class='views'>"
             + "<ul>"
             + "<li><a href='/{{Id}}/io/{{no}}'>I/O</a></li>"
             + "<li><a href='/{{Id}}/state/{{no}}'>State</a></li>"
             + "<li><a href='/{{Id}}/recipe/{{no}}'>Recipe</a></li>"
             + "<li><a href='/{{Id}}/id/{{no}}'>Id</a></li>"
             + "</ul>"
             + "</aside>"
             + "<footer>"
             + "<ul>"
             + "<li>"
             + "<a href='https://github.com/wactbprot/mpvs' target='_blank'>mpvs@github</a></p>"
             + "</li>"
             + "<li>"
             + "<a href='https://github.com/wactbprot/ssmp' target='_blank'>ssmp@github</a></p>"
             + "</li>"
             + "<li>"
             + "<a href='https://github.com/wactbprot/csmp' target='_blank'>csmp@github</a></p>"
             + "</li>"
             + "</ul>"
             + "</footer>"
             + "<script type='text/javascript' src='../../js/jquery-2.1.1.min.js'></script>"
             + "<script type='text/javascript' src='../../js/dl.js'></script>"
             + "</body>"
             + "</html>";
